### ISSUE TITLE
Crashes with throttling render assets

### ISSUE THREAD

**Issue by MalekiRe** [vladbat00/bevy_egui#310]
try
	```commands.insert_resource(
		bevy::render::render_asset::RenderAssetBytesPerFrame::new(4096),
	);```
	Result: crash

```thread '<unnamed>' panicked at /home/malek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_egui-0.29.0/src/egui_render_to_texture_node.rs:250:72:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::renderer::render_system`!
```

**Comment by mvlabat** [comment]
Hi! Are you sure this is an issue with `bevy_egui`? If so, could you provide a more complete example on how to reproduce this?

**Comment by MalekiRe** [comment]
This doesn't actually cause a crash but it causes the window to not render. 

```rust
use bevy::prelude::*;
use bevy_egui::{EguiContexts, EguiPlugin};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(EguiPlugin)
        // Systems that create Egui widgets should be run during the `CoreSet::Update` set,
        // or after the `EguiSet::BeginPass` system (which belongs to the `CoreSet::PreUpdate` set).
        .add_systems(Update, ui_example_system)
        .run();
}

fn ui_example_system(mut contexts: EguiContexts, mut commands: Commands) {
    commands.insert_resource( bevy::render::render_asset::RenderAssetBytesPerFrame::new(4096));
    egui::Window::new("Hello").show(contexts.ctx_mut(), |ui| {
        ui.label("world");
    });
}

```

This one causes it to crash

```rust
use bevy::prelude::*;
use bevy_egui::{EguiContexts, EguiPlugin, EguiRenderToTextureHandle};
use wgpu_types::{Extent3d, TextureUsages};

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins);
    app.add_plugins(EguiPlugin);
    app.add_systems(Startup, setup_worldspace);
    app.add_systems(Update, (update_screenspace, update_worldspace));
    app.run();
}

fn update_screenspace(mut contexts: EguiContexts, mut commands: Commands) {
    commands.insert_resource( bevy::render::render_asset::RenderAssetBytesPerFrame::new(4096));
    egui::Window::new("Screenspace UI").show(contexts.ctx_mut(), |ui| {
        ui.label("I'm rendering to screenspace!");
    });
}

fn update_worldspace(
    mut contexts: Query<&mut bevy_egui::EguiContext, With<EguiRenderToTextureHandle>>,
) {
    for mut ctx in contexts.iter_mut() {
        egui::Window::new("Worldspace UI").show(ctx.get_mut(), |ui| {
            ui.label("I'm rendering to a texture in worldspace!");
        });
    }
}

fn setup_worldspace(
    mut images: ResMut<Assets<Image>>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    mut commands: Commands,
) {
    let output_texture = images.add({
        let size = Extent3d {
            width: 256,
            height: 256,
            depth_or_array_layers: 1,
        };
        let mut output_texture = Image {
            // You should use `0` so that the pixels are transparent.
            data: vec![0; (size.width * size.height * 4) as usize],
            ..default()
        };
        output_texture.texture_descriptor.usage |= TextureUsages::RENDER_ATTACHMENT;
        output_texture.texture_descriptor.size = size;
        output_texture
    });

    commands.spawn(PbrBundle {
        mesh: meshes.add(Cuboid::new(1.0, 1.0, 1.0).mesh()),
        material: materials.add(StandardMaterial {
            base_color: Color::WHITE,
            base_color_texture: Some(Handle::clone(&output_texture)),
            alpha_mode: AlphaMode::Blend,
            // Remove this if you want it to use the world's lighting.
            unlit: true,
            ..default()
        }),
        ..default()
    });
    commands.spawn(EguiRenderToTextureHandle(output_texture));
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(1.5, 1.5, 1.5).looking_at(Vec3::new(0., 0., 0.), Vec3::Y),
        ..default()
    });
}

```

( these are taken from your examples and just inserted the command )

**Comment by mvlabat** [comment]
Thank you for the example! I was able to reproduce the issue.
Btw, moving `commands.insert_resource( bevy::render::render_asset::RenderAssetBytesPerFrame::new(4096));` to the setup system fixes rendering in screen-space, but the worldspace rendering still crashes for me at

```
thread 'main' panicked at src/egui_render_to_texture_node.rs:248:72:
called `Option::unwrap()` on a `None` value
```

**Comment by vladbat00** [comment]
This will be fixed by #326.
